-- Read .env.json if it exists (generated by NixOS)
local nixos_env = {}
local env_file = vim.fn.expand("~/.config/.env.json")
if vim.fn.filereadable(env_file) == 1 then
    local content = vim.fn.readfile(env_file)
    nixos_env = vim.json.decode(table.concat(content, "\n")) or {}
end

return {
    prettier = {
        ft = { 'typescriptreact', 'typescript', 'javascript', 'css', 'html', 'json', 'yaml' }
    },
    auto_save = {
        debounce = 200
    },
    options = {
        nvim_tree = true,
    },
    java_17_home = nixos_env.java_17_home or "/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home",
    java_21_home = nixos_env.java_21_home or "/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home",
    jdtls_home = nixos_env.jdtls_home or "/opt/homebrew/opt/jdtls/libexec",
    jdtls_bin = nixos_env.jdtls_bin,  -- nil on macOS, use java directly
    java_debug_jar = nixos_env.java_debug_jar,  -- NixOS: path to java-debug jar
    java_test_jars = nixos_env.java_test_jars,  -- NixOS: path to java-test jars directory
    lombok_jar = nixos_env.lombok_jar,  -- NixOS: path to lombok jar
}
