local defaults = require "u.defaults"
local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ":p:h:t")
local cache_dir = "/mnt/psf/nvmecased/jdtls-cache"
local workspace_dir = cache_dir .. "/workspace/" .. project_name

-- Debug bundles for nvim-dap
local bundles = {}
-- NixOS: use paths from defaults (generated by configuration.nix)
if defaults.java_debug_jar and vim.fn.filereadable(defaults.java_debug_jar) == 1 then
  table.insert(bundles, defaults.java_debug_jar)
else
  -- Fallback: manual installation path
  local java_debug_path = vim.fn.glob(vim.fn.stdpath("data") .. "/java-debug/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-*.jar", true)
  if java_debug_path ~= "" then
    table.insert(bundles, java_debug_path)
  end
end
-- Add vscode-java-test bundles if available
if defaults.java_test_jars and vim.fn.isdirectory(defaults.java_test_jars) == 1 then
  vim.list_extend(bundles, vim.split(vim.fn.glob(defaults.java_test_jars .. "/*.jar", true), "\n"))
else
  -- Fallback: manual installation path
  local java_test_path = vim.fn.stdpath("data") .. "/vscode-java-test/server"
  if vim.fn.isdirectory(java_test_path) == 1 then
    vim.list_extend(bundles, vim.split(vim.fn.glob(java_test_path .. "/*.jar", true), "\n"))
  end
end

-- Read project-specific settings from .jdtls/settings.json if exists
local project_settings = {}
local settings_file = vim.fn.getcwd() .. "/.jdtls/settings.json"
if vim.fn.filereadable(settings_file) == 1 then
  local content = vim.fn.readfile(settings_file)
  project_settings = vim.json.decode(table.concat(content, "\n")) or {}
end

-- Lombok support
local lombok_jar = defaults.lombok_jar
if not lombok_jar or vim.fn.filereadable(lombok_jar) ~= 1 then
  -- Fallback: check common locations
  local fallback_paths = {
    vim.fn.expand("~/.local/share/lombok/lombok.jar"),
    "/usr/local/share/lombok/lombok.jar",
  }
  for _, path in ipairs(fallback_paths) do
    if vim.fn.filereadable(path) == 1 then
      lombok_jar = path
      break
    end
  end
end

-- Build cmd based on platform
local cmd
if defaults.jdtls_bin then
  -- NixOS: use the wrapper script
  cmd = {
    defaults.jdtls_bin,
    "-data", workspace_dir,
  }
  -- Add lombok javaagent if available
  if lombok_jar then
    table.insert(cmd, 2, "--jvm-arg=-javaagent:" .. lombok_jar)
  end
else
  -- macOS: call java directly
  local config_dir = defaults.jdtls_home .. "/config_mac"
  cmd = {
    defaults.java_21_home .. "/bin/java",
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=ALL",
    "-Xmx1g",
    "--add-modules=ALL-SYSTEM",
    "--add-opens", "java.base/java.util=ALL-UNNAMED",
    "--add-opens", "java.base/java.lang=ALL-UNNAMED",
    "-jar", vim.fn.glob(defaults.jdtls_home .. "/plugins/org.eclipse.equinox.launcher_*.jar"),
    "-configuration", config_dir,
    "-data", workspace_dir,
  }
  -- Add lombok javaagent if available (insert after java command)
  if lombok_jar then
    table.insert(cmd, 2, "-javaagent:" .. lombok_jar)
  end
end

-- Merge project settings with defaults
local java_settings = vim.tbl_deep_extend("force", {
  home = defaults.java_21_home,
  configuration = {
    runtimes = {
      {
        name = "JavaSE-17",
        path = defaults.java_17_home,
      },
      {
        name = "JavaSE-21",
        path = defaults.java_21_home,
        default = true,
      },
    },
  },
  signatureHelp = { enabled = true },
  contentProvider = { preferred = "fernflower" },
  completion = {
    favoriteStaticMembers = {
      "org.junit.Assert.*",
      "org.junit.jupiter.api.Assertions.*",
      "org.mockito.Mockito.*",
    },
  },
  sources = {
    organizeImports = {
      starThreshold = 9999,
      staticStarThreshold = 9999,
    },
  },
}, project_settings)

return {
  cmd = cmd,
  root_markers = { ".git", "mvnw", "gradlew", "pom.xml", "build.gradle" },
  settings = {
    java = java_settings,
  },
  init_options = {
    bundles = bundles,
  },
}
