# vim style tmux config
set -sg escape-time 0
set -g base-index 1
setw -g pane-base-index 1

# use C-a, since it's on the home row and easier to hit than C-b
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

# Easy config reload
bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# vi is good
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"


bind-key -T prefix v split-window -h
bind-key -T prefix x split-window -v
bind-key -T prefix H previous-window
bind-key -T prefix h select-pane -L
bind-key -T prefix j select-pane -D
bind-key -T prefix k select-pane -U
bind-key -T prefix l select-pane -R

bind-key -T prefix L next-window
bind-key -T prefix r command-prompt -p "Rename window:" "rename-window '%%'"
bind-key -T prefix W command-prompt -p "New window:" "new-window -n '%%'"
bind-key -T prefix m display-panes \; command-prompt -p "Move to pane:" "swap-pane -t '%%'"
bind-key -T prefix S command-prompt -p "New session:" "new-session -A -s '%%'"

# resize pane
bind-key -r -T prefix       Up                 resize-pane -U 5
bind-key -r -T prefix       Down               resize-pane -D 5
bind-key -r -T prefix       Left               resize-pane -L 5
bind-key -r -T prefix       Right              resize-pane -R 5

# close window
bind-key    -T prefix       C                    confirm-before -p "kill-window #W? (y/n)" kill-window
bind-key    -T prefix       c                    kill-pane
bind-key    -T prefix       a                    last-pane
bind-key    -T prefix       Space                last-window

